services:
  mysql:
    image: 'mysql:latest'
    ports:
      - '3307:3306'
    environment:
      - 'MYSQL_DATABASE=employee_management_system'
      - 'MYSQL_ROOT_PASSWORD=admin123'
      # - 'MYSQL_PASSWORD=secret'
      # - 'MYSQL_USER=myuser'
    volumes:
      - ./mysql_data:/var/lib/mysql

  # backend-app:
  #   ports:
  #     - "8086:8086"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_management_system?createDatabaseIfNotExist=true
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: admin123
  #   depends_on:
  #     - mysql
    # ports:
    #   - '3306:3306'
