services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=employee_management_system'
      - 'MYSQL_ROOT_PASSWORD=admin123'
      # - 'MYSQL_PASSWORD=secret'
      # - 'MYSQL_USER=myuser'
    backend-app:
      build:
        context: ./java-backend
        dockerfile: Dockerfile
    ports:
      - '3306:3306'
